# Generated by Django 4.2.1 on 2023-06-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='creates_on',
            new_name='created_on',
        ),
    ]
