# Generated by Django 4.2.1 on 2023-06-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_creates_on_profile_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Message',
            new_name='message',
        ),
    ]
